### ISSUE TITLE
Strategy to init WorkbenchModule

### ISSUE THREAD

**Issue by ryppo** [dlemmermann/WorkbenchFX#6]
At first, WorkbenchFX is really great. Thank you for that.
The case: In my WorkbenchModule I add a ToolbarItem to the ModuleToolbar. Based on v1.0.0 I have two possibilities: Add this code to the constructor or override 'init(Workbench workbench)'.
The point is, I need to use the workbench object. Only the 'init' method provides it. But using this method calls my code (to fill the toolbar) multiple times while using the application (the reason is clear for me). And this will add my toolbaritems again and again.
Based on this behaviour I have to check if the method was called the first time, only then I execute the code.
Ok, this is simple. But it would be more intuitive, to have a support for this.
Proposal: class 'WorkbenchModule' provides a further empty method (to override), which is called only once after init. Means, even if init is called again, based on the known state, the new method is not called again.
What do you think?

**Comment by martinfrancois** [comment]
Hi @ryppo!
Thanks for the praise, we're glad you like it! 👍 
We thought about adding a method like that, but we had issues coming up with a clear and self-explanatory name and even more importantly, we couldn't come up with a use case that made sense.
You correctly identified the two possibilities however! We intended to have `ToolbarItem`s added in the constructor actually, since like you mentioned, the `init()` method isn't guaranteed to only run once. This was perfectly acceptable for us, as we couldn't think of any reason why someone would need the `Workbench` for a `ToolbarItem`.
Could you please elaborate your use case in a bit more detail? I would be interested in knowing what kind of use case would require a `ToolbarItem` to require a `Workbench` object.

I think what would be a better approach than to use `init()` and to check whether the `ToolbarItem`s were already added. If you have a look at most of the controls we use that require the `Workbench`, like for example the [`NavigationDrawer`](https://github.com/dlemmermann/WorkbenchFX/blob/master/workbenchfx-core/src/main/java/com/dlsc/workbenchfx/view/controls/NavigationDrawer.java), you will see that we don't require the `Workbench` object in the constructor. Instead, we use an `ObjectProperty<Workbench>` and you could do the same in your `ToolbarItem`, calling `toolbarItem.setWorkbench(getWorkbench())` in the `init()` method. After that, we usually either apply a listener / binding to it or whenever possible we simply use `getWorkbench()` instead of referencing the `Workbench` object directly, if calls are guaranteed to happen after `setWorkbench()` was called.
While I agree that this is a bit more of a complex solution, I think it's quite a clean solution, since it also allows you to dereference the `Workbench` object in the `destroy()` method, allowing you to react to this with the property of the `Workbench` in your `ToolbarItem` and to clean up there as well.

Please tell me what you think and I'm looking forward to hearing about your use case. If it makes sense, I think we could consider adding it.

**Comment by ryppo** [comment]
Hi @martinfrancois ✌️
your deep explaination of the design suggestions are very helpful to understand it.
Indeed, the current implementation of 'WorkbenchModule' brought me an NPE - at the beginning. Because I was using 'getWorkbench()' too early. Anyway, I saw the source code and changed my implementation.
Back to the current case.
Using the great JPro framework (version 2018.1.6), there is a special implementation necessary to provide a 'FileChooser' behavior to the 'Button' (in 'ToolbarItem'). You need to use the 'WebAPI' feature 'makeFileUloadNode'. There is just this issue to get the current 'WebAPI'. For this there is a feature 'WebAPI.getWebAPI(Scene)'. And here is the use case: The 'Scene' is not available from 'WorkbenchModule', but from 'Workbench'.
Okay, this is really a special case. Initially I thought to provide the WebAPI within the 'WorkbenchModule' constructor. But I think this is not good code. Because generally this object is available in 'WorkbenchModule' - just a little bit late.
This explains, why I create the 'ToolbarItem' in 'init' method, instead of in the constructor.

Another solution would be, if the 'Scene' is known in constructor of 'WorkbenchModule'.

I hope my explanation is not too complex 😁

**Comment by martinfrancois** [comment]
Hi @ryppo ✌️ 
I'm glad my explanations helped with your understanding!

I see, although I have to admit I'm not sure I really understood what the problem is.
If I understood your problem correctly, would an approach like this work? (Pseudocode)
```java
class MyModule extends WorkbenchModule {
  ToolbarItem button;
  MyModule() {
    super("My Module", ...);
    button = new ToolbarItem(...);
    getToolbarControlsLeft(button);
  }
  @Override void init(Workbench workbench) {
    WebAPI.makeFileUloadNode(button, WebAPI.getWebAPI(workbench.getScene())); // I don't know what you actually want to do here, this is a placeholder to show you what I think you could use
  }
}
```

If my proposal doesn't work for a certain reason, please provide me with the concrete code you had to use in your implementation, so I can better understand why it is needed.

**Comment by ryppo** [comment]
Hi @martinfrancois 
thank you, this is one of the possible useful approaches - and it's a quite better minimal solution :-)
Just to have as good code as possible, I like searching for improvements.
To explain: In your example the most code is executed only once, as expected. But the code in init is called more often than necessary. And reason is only the availability of the Workbench.
Of course, I don't want to break the design. My question is answered. Thank you.

**Comment by martinfrancois** [comment]
Hi @ryppo!
You're welcome! I definitely see what you mean. We definitely discussed this, but we thought the additional complexity definitely outweighs the advantages you get by having this opportunity, as most of the times the calls being made in `init()` that are being called multiple times are not an issue at all. However, I will still leave the option open to include something like this in the future, if there is a plausible use case that would have a significant benefit from only running at the first initialization of the module.
I'm glad your question is answered! If a use case comes up in which it would make a significant difference, don't hesitate to open up an issue!
